name: hack
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  webview_flutter: ^3.0.4
  intl: ^0.18.1  # For time formatting
  timer_builder: ^2.0.0  # For timed updates
  firebase_core: ^3.9.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1
flutter_icons:
  image_path: 'assets/app_icon.png'
  ios: true
  android: true

flutter:
  uses-material-design: true

