// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC69XX-12mG9hdhgfSS3yAC-Fg99SBEXro',
    appId: '1:657916112511:web:56c96faa147ea2b23a194a',
    messagingSenderId: '657916112511',
    projectId: 'my-hack-app-1',
    authDomain: 'my-hack-app-1.firebaseapp.com',
    storageBucket: 'my-hack-app-1.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBJlgUVqICaEv3ibCVYaTC4IQdSsnIaz4k',
    appId: '1:657916112511:android:a0e072d79933df0d3a194a',
    messagingSenderId: '657916112511',
    projectId: 'my-hack-app-1',
    storageBucket: 'my-hack-app-1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDHqrbAXbOgyXIawZfjH5atrCPcriaNCCY',
    appId: '1:657916112511:ios:b6e0d0b7eec772003a194a',
    messagingSenderId: '657916112511',
    projectId: 'my-hack-app-1',
    storageBucket: 'my-hack-app-1.firebasestorage.app',
    iosBundleId: 'com.example.hack',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDHqrbAXbOgyXIawZfjH5atrCPcriaNCCY',
    appId: '1:657916112511:ios:b6e0d0b7eec772003a194a',
    messagingSenderId: '657916112511',
    projectId: 'my-hack-app-1',
    storageBucket: 'my-hack-app-1.firebasestorage.app',
    iosBundleId: 'com.example.hack',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC69XX-12mG9hdhgfSS3yAC-Fg99SBEXro',
    appId: '1:657916112511:web:a1a675548f272d6f3a194a',
    messagingSenderId: '657916112511',
    projectId: 'my-hack-app-1',
    authDomain: 'my-hack-app-1.firebaseapp.com',
    storageBucket: 'my-hack-app-1.firebasestorage.app',
  );

}